name: versionarte
description: Force update, show update indicator and disable the app for maintenance with total freedom over the UI.
version: 2.0.0
repository: https://github.com/kamranbekirovyz/versionarte
issue_tracker: https://github.com/kamranbekirovyz/versionarte/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_remote_config: ^5.4.2
  http: ^1.3.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# screenshots:
  # - description: versionarte package